### PR TITLE
Add list metrics command

### PR DESCRIPTION
**Pull request by hanahmily**
List all of metrics:

image

Filter metrics based on "regex"
image

Get service relevant metrics:
image

Signed-off-by: Gao Hongtao <hanahmily@gmail.com>

### CODE REVIEW

**Review by kezhenxu94 — COMMENTED** [review]
Can you please update the doc as well?

**Comment by wu-sheng** [comment]
Just curious, the HAP adaptor will use CLI internally?

**Comment by hanahmily** [comment]
> Can you please update the doc as well?

done.

**Comment by hanahmily** [comment]
> Just curious, the HAP adaptor will use CLI internally?

Here is the HPA external metrics we could opt to
```
metric:
      name: queue_messages_ready
      selector: "queue=worker_tasks"
```

swctl query pattern, GraphQL expressions free and key-value flags, fits the label system of HPA selector.

**Review by wu-sheng — APPROVED** [review]

**Review by kezhenxu94 — APPROVED** [review]
LGTM

**Pull request merged**
