### PR TITLE
Use template files in yaml format instead

### PR DESCRIPTION
**Pull request by fgksgf**
The original template file uses the `json` format, but `json` does not support comments and its readability is poor, so we decided to use the `yaml` format instead.

First, I rewrote the template file in `yaml` format, as an initial version to be discussed. Once the final format is determined, I will modify the corresponding code.

Besides, we need discuss:
+ Do we need use  [viper](https://github.com/spf13/viper) to manage configuration?
+ Are there other commands that need template files? If so, we need determine their format too.

### CODE REVIEW

**Comment by kezhenxu94** [comment]
> + Do we need use  [viper](https://github.com/spf13/viper) to manage configuration?

As we begin to tackle yaml configurations, it's ok to introduce viper lib, there should be many defaults that can save us a lot of time by viper

> + Are there other commands that need template files? If so, we need determine their format too.

For now, the other commands' options are not very complex, and they can share the same default values, so we just consider the dashboard command at the moment

**Comment by wu-sheng** [comment]
By reading the config file, is this file requiring manual configuration? It doesn't look like the one from UI-template service.

**Comment by fgksgf** [comment]
> is this file requiring manual configuration? 

The config file is default, only when users want to customize the dashboard (like changing colors of widgets, items to be displayed), they need manual configuration. The effect is similar to [this](https://github.com/apache/skywalking-cli/pull/46#issuecomment-664100438).

> It doesn't look like the one from UI-template service.

It seems there is currently no specification for UI-template. So we decide to define a format and the default template by ourselves.

**Comment by fgksgf** [comment]
@kezhenxu94 If you think this `yaml` template is ok, I'll move on with it.

**Review by kezhenxu94 — APPROVED** [review]
LGTM

**Pull request merged**
