### PR TITLE
Support continuous profiling related sub-commands

### PR DESCRIPTION
**Pull request by mrproliu**
1. `profiling continuous set`: set the continuous profiling policy to a service.
2. `profiling continuous list`: query the continuous profiling policy in a service. 
3. `profiling ebpf list`: add the `triggerType` parameter for the continuous profiling task query. 
4. `metrics`: adopt the "scope" parameter in the metrics-related sub-command.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Could you share what is the command(s) added here?

**Comment by mrproliu** [comment]
Yes, I have descript the commands in the PR description.

**Comment by wu-sheng** [comment]
> metrics: adopt the "range" parameter in the metrics-related sub-command.

What do you mean `range`? I don't remember we changed metrics query GraphQL.

**Comment by mrproliu** [comment]
Oh, update to the "scope", I typed the wrong word.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
