### PR TITLE
Refactor project to use goapi

### PR DESCRIPTION
**Pull request by fgksgf**
- [x] Remove git submodules
- [x] Remove gen codes and graphql api
- [x] Update makefile and readme

### CODE REVIEW

**Comment by kezhenxu94** [comment]
CI failed, codes LGTM, thanks for the quick reaction!!

**Review by kezhenxu94 — APPROVED** [review]
thanks

**Comment by fgksgf** [comment]
> CI failed, codes LGTM, thanks for the quick reaction!!

The project looks much compact. BTW, does goapi need release ?

**Comment by kezhenxu94** [comment]
> > CI failed, codes LGTM, thanks for the quick reaction!!
> 
> The project looks much compact. BTW, does goapi need release ?

It would be nice if goapi can be released so that we have clear change logs between releases, though it's not a must.

@hanahmily FYI this PR is merged

**Pull request merged**
