### PR TITLE
Add screenshots for use cases

### PR DESCRIPTION
**Pull request by fgksgf**

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Images are too large, loading them in the page takes too long, please resize the images to ~100KB or so

**Comment by wu-sheng** [comment]
screenshots are usually hosted in the SkyWalking website, as Apache has mirror over the world. And the GitHub as a mirror system once you are referring to a static URI.

**Comment by kezhenxu94** [comment]
> screenshots are usually hosted in the SkyWalking website, as Apache has mirror over the world. And the GitHub as a mirror system once you are referring to a static URI.

So @fgksgf move the images to the skywalking-website and use URLs to reference here

**Comment by fgksgf** [comment]
> > screenshots are usually hosted in the SkyWalking website, as Apache has mirror over the world. And the GitHub as a mirror system once you are referring to a static URI.
> 
> So @fgksgf move the images to the skywalking-website and use URLs to reference here

Done, you can click [here](https://github.com/fgksgf/skywalking-cli/tree/doc#use-cases) to preview.

**Review by kezhenxu94 — APPROVED** [review]

**Pull request merged**
