### PR TITLE
Move `parseScope` to pkg

### PR DESCRIPTION
**Pull request by fgksgf**

### CODE REVIEW

**Comment by hanahmily** [comment]
After reading relevant cli codes, could we refactor followings

1. Move action functions from `internal/commands` to `pkg/commands`. For example:

`pkg/commands/metrics/linear/linear-metrics.go`

```go
func Linear(ctx *cli.Context) (api.MetricsValues, Error){
                 end := ctx.String("end")
		start := ctx.String("start")
		step := ctx.Generic("step")

		metricsName := ctx.String("name")
		entity := interceptor.ParseEntity(ctx)

		duration := api.Duration{
			Start: start,
			End:   end,
			Step:  step.(*model.StepEnumValue).Selected,
		}

		metricsValues, err := metrics.LinearIntValues(ctx, api.MetricsCondition{
			Name:   metricsName,
			Entity: entity,
		}, duration)

		if err != nil {
			return nil, err
		}
                return metricsValues, nil
}
```

`internal/commands/metrics/linear/linear-metrics.go`

```go
Action: func(ctx *cli.Context) error {
		metricsValues, err := pkglinear.Linear(ctx)
                 if err != nil {
                    return err
                 }
		return display.Display(ctx, &displayable.Displayable{Data: utils.MetricsValuesToMap(duration, metricsValues)})
	},
```

The above convention will simplify the usage of CLI API. BTW, the event relevant API is missing in `pkg`.

**Comment by hanahmily** [comment]
2. What's the purpose of introducing a submodule to `gen-codes/skywalking/network`? If other projects would like to import cli, they have to `replace` this repo in their `go.mod` like swck did https://github.com/apache/skywalking-swck/blob/master/go.mod#L28

**Comment by kezhenxu94** [comment]
@hanahmily are you seeing the latest codes? I think your comments above is what we do currently

**Comment by kezhenxu94** [comment]
> 1. What's the purpose of introducing a submodule to `gen-codes/skywalking/network`? If other projects would like to import cli, they have to `replace` this repo in their `go.mod` like swck did https://github.com/apache/skywalking-swck/blob/master/go.mod#L28

We have command to report events (recently introduced)

**Comment by fgksgf** [comment]
@kezhenxu94 could you help check the CI ?

**Review by kezhenxu94 — APPROVED** [review]
@fgksgf if you have time, please also consider refactoring the other commands' logics into pkg like what you did to event report command, thanks

**Pull request merged**
