### PR TITLE
Change the default TZ to the local TZ

### PR DESCRIPTION
**Pull request by innerpeacez**
As the title

### CODE REVIEW

**Comment by innerpeacez** [comment]
Since time.Now() is used to obtain time in both duration.go and duration_test.go, theoretically there are cases where the time is not the same twice, but I have not found any other good way.

**Comment by wu-sheng** [comment]
Actually, this TZ logic is not that right. TZ and current time should get from OAP server. We have the GraphQL for this. @kezhenxu94 Could you submit an issue for this? We should change this logic in 0.2.0.

**Comment by kezhenxu94** [comment]
> Actually, this TZ logic is not that right. TZ and current time should get from OAP server. We have the GraphQL for this. @kezhenxu94 Could you submit an issue for this? We should change this logic in 0.2.0.

This patch fixes partially, and it serves as a fallback when the OAP server is older than 6.4.0(when the TZ API is not yet introduced, not sure the exact version), I'll create an issue to track this

**Comment by wu-sheng** [comment]
Back forward compatibility is reasonable. I am OK to merge this.

**Pull request merged**
