### PR TITLE
feat: add fish and zsh completion support

### PR DESCRIPTION
**Pull request by chenrui333**
would be nice to also support fish and zsh completions. (seeing the completions while reviewing https://github.com/Homebrew/homebrew-core/pull/202118)

### CODE REVIEW

**Comment by wu-sheng** [comment]
@CodePrometheus What is the release policy for us to push further releases there?

You should update cli docs about that.

**Comment by wu-sheng** [comment]
@chenrui333 Please fix CI.

**Comment by CodePrometheus** [comment]
> @CodePrometheus What is the release policy for us to push further releases there?

I have added swctl to autobump, the robot will automatically update it after we release the version. 

> You should update cli docs about that.

I will update the brew usage instructions in README after swctl is pushed in [Homebrew](https://brew.sh/)

**Comment by wu-sheng** [comment]
Are they monitoing git tag or somewhere for our release?

**Comment by CodePrometheus** [comment]
> Are they monitoing git tag or somewhere for our release?

AFAIK, homebrew's bot triggers `brew bump` for the formula to be autobumped every three hours through github-actions, it will get releases/latest through `api.github.com` based on the information I configured (repo, url, etc.).
@chenrui333  Please kindly correct me if I'm wrong, thanks :)

**Review by CodePrometheus — APPROVED** [review]

**Pull request merged**
