### PR TITLE
Fix quick install

### PR DESCRIPTION
**Pull request by BFergerson**
see https://github.com/apache/skywalking-cli/pull/106#discussion_r684621030

The additional `tree` path results in 404.

### CODE REVIEW

**Comment by BFergerson** [comment]
This change alone doesn't seem to fix the quick install, btw. The files that get downloaded (from https://apache.website-solution.net) with this install do not match https://downloads.apache.org/skywalking/cli/0.9.0/skywalking-cli-0.9.0-bin.tgz.sha512.

**Comment by wu-sheng** [comment]
https://apache.website-solution.net/ seems not an official ASF site. Is it a mirror?

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
> This change alone doesn't seem to fix the quick install, btw. 

What do you mean `doesn't seem to fix`? Is there any issue of the document?

**Comment by BFergerson** [comment]
It should be failing the signature check https://github.com/apache/skywalking-cli/blob/39dce3dea9f5fdd26e03163a47214d4c0c4fee9d/scripts/install.sh#L64

Whenever I run it, it just hangs:
```sh
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/apache/skywalking-cli/master/scripts/install.sh)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21681  100 21681    0     0   109k      0 --:--:-- --:--:-- --:--:--  109k
The latest version of swctl is 0.9.0
```

**Comment by wu-sheng** [comment]
I downloaded binary and sha512 from the official site, https://dist.apache.org/repos/dist/release/skywalking/cli/0.9.0/

And sha512 check passed through this
``` shell
> shasum -c skywalking-cli-0.9.0-bin.tgz.sha512
skywalking-cli-0.9.0-bin.tgz: OK
```

**Comment by wu-sheng** [comment]
@fgksgf @kezhenxu94 Could you check this?

**Comment by BFergerson** [comment]
The install script installs the un-official https://apache.website-solution.net/skywalking/cli/0.9.0/skywalking-cli-0.9.0-bin.tgz

**Comment by wu-sheng** [comment]
This should be fixed. all release should be from official https://archive.apache.org/dist/skywalking/cli/

**Comment by BFergerson** [comment]
The hashes match now... I'm not sure why the install script hangs then.

**Comment by wu-sheng** [comment]
image

Password required popup.

**Comment by wu-sheng** [comment]
I am feeling this is Chinese mirror.

**Comment by wu-sheng** [comment]
@BFergerson Have you tried to changed `https://apache.website-solution.net` to `https://archive.apache.org/dist/skywalking/cli/`, and try again?

**Pull request merged**
