### PR TITLE
Let the eBPF profiling could performs by service level

### PR DESCRIPTION
**Pull request by mrproliu**
Follow https://github.com/apache/skywalking/issues/8833

Command screenshots:
image
image
image

### CODE REVIEW

**Comment by wu-sheng** [comment]
So, you have implemented this at OAP side(local version), right?

**Comment by mrproliu** [comment]
@kezhenxu94 could you help check on the CI? I have tried it on the local machine and it was successful, the golangci-lint version is the same as the CI.
image

**Comment by fgksgf** [comment]
This may be caused by the go version, since we didn't use `setup-go`, the `golangci-lint` action installed go1.18 automatically:
image

How about adding a step before `golangci-lint`:
```yaml
- uses: actions/setup-go@v3
  with:
    go-version: 1.16
```

**Comment by mrproliu** [comment]
@fgksgf It's not working too :(

**Comment by fgksgf** [comment]
Just find [this](https://github.com/golangci/golangci-lint-action/issues/435#issuecomment-1086174073), updated to v3 works now.

**Comment by mrproliu** [comment]
@fgksgf Yes, I have updated and it works.

**Review by wu-sheng — APPROVED** [review]

**Review by kezhenxu94 — APPROVED** [review]

**Pull request merged**
